version: '3.9'

services:
    arango:
        container_name: ArangoDB
        image: arangodb:latest
        restart: unless-stopped
        env_file:
        - ./.env/
        environment:
            ARANGO_ROOT_PASSWORD: ${ARANGODB_ROOT_PASSWORD}
        ports:
            - 8529:8529
        volumes:
            - arangodb_data:/var/lib/arangodb3
            - arangodb_apps_data:/var/lib/arangodb3-apps

volumes:
    arangodb_data:
    arangodb_apps_data: