services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env/
    environment:
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network
    restart: unless-stopped


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 8888:80
    env_file:
      - ./.env/
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres-network
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  postgres-network:
    name: postgres-network
    driver: bridge